name: Tests

on: [push, pull_request]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Setup Conda
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: false
        update-conda: true
        conda-channels: conda-forge

    - name: Install on Python ${{ matrix.python-version }}
      shell: bash -l {0}
      run: |
        conda create --name TEST python=${{ matrix.python-version }} --file requirements.txt --file requirements-dev.txt
        source activate TEST
        python -m pip install -e . --no-deps --force-reinstall
        python -m pip install -r requirements-dev.txt

    - name: Print environment info to aid w/ debugging.
      shell: bash -l {0}
      run: |
        source activate TEST
        which python

    - name: Run Tests
      shell: bash -l {0}
      run: |
        source activate TEST
        python -m pytest -rxs --cov=pyobis tests

    - name: Run Linter
      run: python -m flake8 ./pyobis/
